[package]
name = "create_option"
version = "0.1.0"
description = "Epicentral Labs - OPX - Create Option"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "create_option"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
common = { path = "anchor/../" }
